# Generated by Django 5.2.3 on 2025-07-30 02:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='URLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('tarih', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kullanıldığı tarih')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'metin',
                'verbose_name_plural': 'metinler',
                'db_table': 'girilen_urls',
                'ordering': ['-tarih'],
            },
        ),
    ]
